name: CD # Continuous Deployment

permissions:
  contents: read

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    if: startsWith(github.event.release.name, 'youtui-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install linux deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends git libasound2-dev pkg-config makepkg
      - name: Echo package name
        run: |
          echo ${{ github.event.release.name }}
      - name: Clone aur
        run: |
          git clone https://aur.archlinux.org/youtui.git
          cd youtui && ls 
