name: Release-plz

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - &install-linux-deps
        name: Install linux deps
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libasound2-dev pkg-config
      - name: Run release-plz
        id: release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # Code to run post-release
      #
      # Add youtui release status and version number to use in the next actions
      - name: Check if youtui was released
        id: check_youtui_release
        if: ${{ steps.release-plz.outputs.releases_created == 'true' }}
        env:
          RELEASES: ${{ steps.release-plz.outputs.releases }}
        run: |
          YOUTUI_IS_RELEASED=$(jq -r 'any(.[]; .package_name == "youtui")' <<< "$RELEASES")
          echo "Checking if youtui was released: $YOUTUI_IS_RELEASED"
          echo "youtui_released=$YOUTUI_IS_RELEASED" >> "$GITHUB_OUTPUT"
          
          if [ "$YOUTUI_IS_RELEASED" == "true" ]; then
             YOUTUI_VERSION=$(jq -r '.[] | select(.package_name == "youtui") | .version' <<< "$RELEASES")
             echo "released version: $YOUTUI_VERSION"
             echo "youtui_version=$YOUTUI_VERSION" >> "$GITHUB_OUTPUT"
          fi

      - name: Release youtui to AUR
        if: ${{ steps.check_youtui_release.outputs.youtui_released == 'true' }}
        env:
          NEW_YOUTUI_VERSION: ${{ steps.check_youtui_release.outputs.youtui_version }}
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          RUNNER_TEMP_DIR: ${{ runner.temp }}
        run: |
          # Grab host IDs to prevent Docker permission errors
          HOST_UID=$(id -u)
          HOST_GID=$(id -g)
          
          # It's safe to write this key to a temporary file - VM is torn down on exit.
          # However - use GitHub Actions nominated temp directory.
          # 
          # Trap is used to prevent subsequent actions having access to this file if somehow this
          # script is aborted before it's deleted (the trap command is run on exit).
          KEY_PATH="$RUNNER_TEMP_DIR/aur_key"
          trap 'rm -f "$KEY_PATH"' EXIT
          echo "$AUR_SSH_PRIVATE_KEY" > "$KEY_PATH"
          chmod 600 "$KEY_PATH"

          # Build an arch linux image set up for AUR development
          docker build \
            --build-arg HOST_UID=$HOST_UID \
            --build-arg HOST_GID=$HOST_GID \
            -t aur-builder \
            -f .github/workflows/Dockerfile.aur-release .

          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -v "$KEY_PATH:/home/builder/.ssh/id_rsa:ro" \
            -e NEW_YOUTUI_VERSION="$NEW_YOUTUI_VERSION" \
            aur-builder \
            /bin/bash -c '
              git config --global --add safe.directory /workspace &&
              git config --global user.email "nick42d-bot@users.noreply.github.com" &&
              git config --global user.name "nick42d-bot" &&
              just release-youtui-to-aur "$NEW_YOUTUI_VERSION"
            '

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - *install-linux-deps
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
